// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY'] ?? '',
    appId: '1:218013895617:android:851f9922bd38e99d777d40',
    messagingSenderId: '218013895617',
    projectId: 'mfashaapp-dfd3b',
    storageBucket: 'mfashaapp-dfd3b.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY'] ?? '',
    appId: '1:218013895617:ios:c8c1adeafbf57442777d40',
    messagingSenderId: '218013895617',
    projectId: 'mfashaapp-dfd3b',
    storageBucket: 'mfashaapp-dfd3b.firebasestorage.app',
    iosBundleId: 'com.example.mfashaApp',
  );
}