// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZ83KkHnhAuKUohG8IA7dq4BDXZn87D4',
    appId: '1:218013895617:android:851f9922bd38e99d777d40',
    messagingSenderId: '218013895617',
    projectId: 'mfashaapp-dfd3b',
    storageBucket: 'mfashaapp-dfd3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfmvmVbBpj3nDqPkBFQX5R19ZuH5zbt6k',
    appId: '1:218013895617:ios:c8c1adeafbf57442777d40',
    messagingSenderId: '218013895617',
    projectId: 'mfashaapp-dfd3b',
    storageBucket: 'mfashaapp-dfd3b.firebasestorage.app',
    iosBundleId: 'com.example.mfashaApp',
  );
}
